version: "3.4"

services:
  app:
    image: article-fed
    container_name: article-feed
    restart: on-failure
    # restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
